
replicaCount: 1

image:
  repository: kennethreitz/httpbin
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources: {
  requests: {
    memory: 100Mi,
    cpu: 0.1
  },
  limits: {
    memory: 100Mi,
    cpu: 0.1
  }
}

mapping:
  enable: true

